In [1]:
import numpy as np

#### Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел от 12 до 24 невключительно

In [2]:
a = np.arange(12, 24, 1)
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

#### Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.

In [3]:
arr_1 = a[:6].reshape(2, 3)
arr_2 = a[:6].reshape(3, 2)
arr_3 = a[:8].reshape(4, 2)
arr_4 = a[:8].reshape(2, 4)
arr_5 = a.reshape(3, 4)
arr_1, arr_2, arr_3, arr_4, arr_5

(array([[12, 13, 14],
        [15, 16, 17]]),
 array([[12, 13],
        [14, 15],
        [16, 17]]),
 array([[12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]))

#### Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк).

In [4]:
arr_1 = a.reshape(-1, 2)
arr_2 = a.reshape(-1, 3)
arr_3 = a.reshape(-1, 4)
arr_4 = a.reshape(3, -1)
arr_5 = a.reshape(2, -1)
arr_1, arr_2, arr_3, arr_4, arr_5

(array([[12, 13],
        [14, 15],
        [16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]),
 array([[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]),
 array([[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]))

#### Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?

In [5]:
print(f'Нет, кол-во измерений = {np.ndim(np.array([[1], [2], [3], [4], [5], [6], [7], [8], [9], [10], [11], [12]]))}')

Нет, кол-во измерений = 2


#### Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.

In [6]:
b1 = np.random.randn(3, 4)
b2 = b1.flatten()
b1.size == b2.size

True

##### Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.

In [7]:
a = np.arange(20, 0, -2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

#### Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. В чем разница между массивами a и b?


In [8]:
b = np.array([np.arange(20, 1, -2)])
print(f'Кол-во измерений (a равно {a.ndim}) != (b равно {b.ndim})')

Кол-во измерений (a равно 1) != (b равно 2)


#### Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10.

In [9]:
a = np.zeros((2, 2))
b = np.ones((3, 2))
v = np.vstack((a, b))
v.size

10

#### Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12. Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов. Получить матрицу At путем транспонирования матрицы A. Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения. Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и почему?


In [10]:
a = np.arange(12)
A = a.reshape(4, 3)
At = A.transpose()
B = A.dot(At)

print(f'Размер B = {B.size}')
print(f'Матрица квадратная т.к. {B.shape[0]} = {B.shape[1]}, значит можем посчитать определитель')
print(f'Обратную матрицу можно получить, если определитель != 0 в нашем варианте он {np.linalg.det(B)}')

Размер B = 16
Матрица квадратная т.к. 4 = 4, значит можем посчитать определитель
Обратную матрицу можно получить, если определитель != 0 в нашем варианте он 0.0


#### Инициализируйте генератор случайных числе с помощью объекта seed, равного 42


In [11]:
np.random.seed(42)

#### Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределенных целых чисел от 0 до 16 невключительно.

In [12]:
c = np.random.randint(0, 16, 16)
c

array([ 6,  3, 12, 14, 10,  7, 12,  4,  6,  9,  2,  6, 10, 10,  7,  4])

#### Поменяйте его форму так, чтобы получилась квадратная матрица C. Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10. Вычислите определитель, ранг и обратную матрицу D_inv для D.

In [13]:
C = c.reshape(4, 4)
D = B + (C * 10)
print(f'Определитель матрицы D = {np.linalg.det(D)}')
print(f'Ранг матрицы D = {np.linalg.matrix_rank(D)}')
D_inv = np.linalg.inv(D)
D_inv

Определитель матрицы D = -28511999.999999944
Ранг матрицы D = 4


array([[ 0.00935396,  0.04486532,  0.05897517, -0.07286055],
       [-0.01503577, -0.00122896, -0.00192971,  0.00967873],
       [-0.00356692, -0.01782828, -0.04152146,  0.04326178],
       [ 0.00909091, -0.00181818,  0.01272727, -0.01090909]])

#### Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице. Убедитесь, что в матрице D_inv остались только нули и единицы. С помощью функции numpy.where, используя матрицу D_inv в качестве маски, а матрицы B и C - в качестве источников данных, получите матрицу E размером 4x4.  Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1, должны быть равны соответствующему элементу матрицы B, а элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 0, должны быть равны соответствующему элементу матрицы C.


In [14]:
D_inv[D_inv < 0] = 0
D_inv[D_inv > 0] = 1
D_inv

array([[1., 1., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [1., 0., 1., 0.]])

In [15]:
E = np.zeros((4, 4))

E[np.where(D_inv == 0)] = C[np.where(D_inv == 0)]
E[np.where(D_inv == 1)] = B[np.where(D_inv == 1)]
E

array([[  5.,  14.,  23.,  14.],
       [ 10.,   7.,  12., 122.],
       [  6.,   9.,   2., 212.],
       [ 32.,  10., 212.,   4.]])